#include<iostream>
using namespace std;
int main(){

    printf("*********************************Volume of a Sphere Program*********************************\n");
    float x = 10;
    float VS;
    cout<<"Radious of the Sphere is = "<<x<<endl;
    cout<<"The formula is 4/3 x 3.1415 x r x r x r";

    VS = 1.3333333 * 3.1415926535 * x * x *x;

    printf("\nThe Volume of circle is : ");
    cout<<VS<<endl;
    return 0;
 

}